name: generate-tags

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1 
    - uses: pattyde/mobile-recipes@master
    - name: Generate recipe tags
      run: tag_generator.py
